# Generated by Django 3.1.5 on 2021-01-17 05:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
